import { NextResponse } from 'next/server';

function detectPlatform(request: Request): 'windows' | 'unix' {
    const userAgent = request.headers.get('user-agent') || '';
    const platformHeader = request.headers.get('x-platform') || '';
    
    if (platformHeader) {
        return platformHeader.toLowerCase() === 'windows' ? 'windows' : 'unix';
    }
    
    if (userAgent.toLowerCase().includes('windows')) {
        return 'windows';
    }
    
    return 'unix';
}

function generateBashScript(host: string, baseUrl: string): string {
    const lines = [
        '#!/bin/bash',
        '# =============================================================================',
        '# Skill-insight One-Click Setup',
        '# =============================================================================',
        '',
        'SKILL_INSIGHT_HOST="' + host + '"',
        'SKILL_INSIGHT_BASE_URL="' + baseUrl + '"',
        'OPENCODE_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"',
        '',
        'echo "🚀 Fetching Skill-insight telemetry components from $SKILL_INSIGHT_BASE_URL..."',
        '',
        '# 1. Setup Directories',
        'mkdir -p "$HOME/.skill-insight"',
        'mkdir -p "$HOME/.skill-insight/logs"',
        'mkdir -p "$HOME/.opencode/plugins"',
        'mkdir -p "$OPENCODE_CONFIG_DIR/plugins"',
        'mkdir -p "$HOME/.opencode/skills"',
        'mkdir -p "$HOME/.claude/projects"',
        'mkdir -p "$HOME/.openclaw/agents"',
        'mkdir -p ".opencode/skills"',
        'echo "📂 Created necessary directories"',
        '',
        '# 2. Interactive Framework Selection with inquirer',
        'echo ""',
        '',
        'SELECTOR_SCRIPT="$HOME/.skill-insight/framework_selector.mjs"',
        'SELECTOR_RESULT="$HOME/.skill-insight/.selector_result"',
        '',
        '# Install inquirer if not already installed',
        'cd "$HOME/.skill-insight"',
        'if [ ! -d "node_modules/inquirer" ]; then',
        '    echo "📦 Installing inquirer for interactive selection..."',
        '    npm install inquirer --save 2>/dev/null',
        'fi',
        '',
        'cat > "$SELECTOR_SCRIPT" << \'SELECTOR_EOF\'',
        'import inquirer from \'inquirer\';',
        'import fs from \'fs\';',
        '',
        'const frameworks = [',
        '    { name: \'OpenCode\', value: \'opencode\' },',
        '    { name: \'Claude Code\', value: \'claude\' },',
        '    { name: \'OpenClaw\', value: \'openclaw\' }',
        '];',
        '',
        'async function select() {',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╔══════════════════════════════════════════════════════════╗\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[1m\\x1b[36m%s\\x1b[0m\', \'║                 ✨ Skill-insight ✨                      ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╚══════════════════════════════════════════════════════════╝\');',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[90m%s\\x1b[0m\', \'  提示: ↑↓ 移动  |  空格 选择  |  a 全选  |  i 反选  |  Enter 确认\');',
        '    console.log(\'\');',
        '',
        '    const answers = await inquirer.prompt([',
        '        {',
        '            type: \'checkbox\',',
        '            name: \'frameworks\',',
        '            message: \'集成到：\',',
        '            choices: frameworks,',
        '            pageSize: 10,',
        '            loop: false',
        '        }',
        '    ]);',
        '',
        '    const selected = answers.frameworks;',
        '    ',
        '    if (selected.length > 0) {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[32m%s\\x1b[0m\', \'✅ 将安装以下组件:\');',
        '        selected.forEach(fw => {',
        '            const name = frameworks.find(f => f.value === fw)?.name || fw;',
        '            console.log(\'\\x1b[32m%s\\x1b[0m\', \'   • \' + name);',
        '        });',
        '        console.log(\'\');',
        '    } else {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[33m%s\\x1b[0m\', \'⚠️  未选择任何组件，将不进行安装。\');',
        '        console.log(\'\');',
        '    }',
        '',
        '    const resultFile = process.env.SELECTOR_RESULT_FILE || process.env.HOME + \'/.skill-insight/.selector_result\';',
        '    fs.writeFileSync(resultFile, selected.join(\',\'));',
        '}',
        '',
        'select().catch(err => {',
        '    console.error(\'Error:\', err);',
        '    process.exit(1);',
        '});',
        'SELECTOR_EOF',
        '',
        '# Run the selector interactively from /dev/tty',
        'export SELECTOR_RESULT_FILE="$SELECTOR_RESULT"',
        'cd "$HOME/.skill-insight" && npx -y tsx "$SELECTOR_SCRIPT" < /dev/tty',
        '',
        '# Read the selection result from file',
        'if [ -f "$SELECTOR_RESULT" ]; then',
        '    SELECTED_FRAMEWORKS=$(cat "$SELECTOR_RESULT")',
        '    rm -f "$SELECTOR_RESULT"',
        'else',
        '    SELECTED_FRAMEWORKS=""',
        'fi',
        '',
        '# Set installation flags based on selection',
        'INSTALL_OPENCODE=false',
        'INSTALL_CLAUDE=false',
        'INSTALL_OPENCLAW=false',
        '',
        'if [[ "$SELECTED_FRAMEWORKS" == *"opencode"* ]]; then',
        '    INSTALL_OPENCODE=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"claude"* ]]; then',
        '    INSTALL_CLAUDE=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"openclaw"* ]]; then',
        '    INSTALL_OPENCLAW=true',
        'fi',
        '',
        '# Exit if nothing selected',
        'if [ "$INSTALL_OPENCODE" = "false" ] && [ "$INSTALL_CLAUDE" = "false" ] && [ "$INSTALL_OPENCLAW" = "false" ]; then',
        '    echo "⚠️  未选择任何框架组件，将跳过插件安装。"',
        '    echo "   继续执行配置步骤..."',
        '    echo ""',
        'fi',
        '',
        '# 3. Download Components',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then',
        '    echo "⏬ Downloading OpenCode Plugin..."',
        '    curl -sSf "$SKILL_INSIGHT_BASE_URL/api/setup/opencode" -o "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.ts"',
        '    cp "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.ts" "$HOME/.opencode/plugins/Witty-Skill-Insight.ts" 2>/dev/null || true',
        '    echo "⏬ Installing OpenCode commands..."',
        '    mkdir -p "$OPENCODE_CONFIG_DIR/commands"',
        '    curl -sSf "$SKILL_INSIGHT_BASE_URL/api/setup/opencode-commands/si-optimizer" -o "$OPENCODE_CONFIG_DIR/commands/si-optimizer.md"',
        '    echo "⏬ Downloading OpenCode TUI Plugin..."',
        '    curl -sSf "$SKILL_INSIGHT_BASE_URL/api/setup/opencode-tui" -o "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.tui.tsx"',
        '    cp "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.tui.tsx" "$HOME/.opencode/plugins/Witty-Skill-Insight.tui.tsx" 2>/dev/null || true',
        '    export TUI_PLUGIN_PATH="$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.tui.tsx"',
        '    export TUI_CONFIG_FILE="$OPENCODE_CONFIG_DIR/tui.json"',
        '    if command -v node &> /dev/null; then',
        '      node - <<\'NODE\'',
        'const fs = require("fs");',
        'const path = require("path");',
        'const file = process.env.TUI_CONFIG_FILE;',
        'const pluginPath = process.env.TUI_PLUGIN_PATH;',
        'let data = {};',
        'try {',
        '  if (fs.existsSync(file)) {',
        '    const text = fs.readFileSync(file, "utf8");',
        '    data = text && text.trim() ? JSON.parse(text) : {};',
        '  }',
        '} catch {}',
        'if (!data || typeof data !== "object") data = {};',
        'const list = Array.isArray(data.plugin) ? data.plugin.slice() : [];',
        'if (pluginPath && !list.includes(pluginPath)) list.push(pluginPath);',
        'data.plugin = list;',
        'fs.mkdirSync(path.dirname(file), { recursive: true });',
        'fs.writeFileSync(file, JSON.stringify(data, null, 2));',
        'NODE',
        '    else',
        '      echo "⚠️  node not found; skip TUI plugin config patch."',
        '    fi',
        'fi',
        '',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then',
        '    echo "⏬ Downloading Claude Code Watcher..."',
        '    curl -sSf "$SKILL_INSIGHT_BASE_URL/api/setup/claude-watcher" -o "$HOME/.skill-insight/claude_watcher_client.ts"',
        'fi',
        '',
        'if [ "$INSTALL_OPENCLAW" = "true" ]; then',
        '    echo "⏬ Downloading OpenClaw Watcher..."',
        '    curl -sSf "$SKILL_INSIGHT_BASE_URL/api/setup/openclaw-watcher" -o "$HOME/.skill-insight/openclaw_watcher_client.ts"',
        'fi',
        '',
        '# 4. Configure ~/.skill-insight/.env',
        'SKILL_INSIGHT_CONFIG_FILE="$HOME/.skill-insight/.env"',
        'EXISTING_KEY=""',
        'EXISTING_HOST=""',
        'EXISTING_SHOW_TASK_STATS=""',
        'if [ -f "$SKILL_INSIGHT_CONFIG_FILE" ]; then',
        '    EXISTING_KEY=$(grep \'^SKILL_INSIGHT_API_KEY=\' "$SKILL_INSIGHT_CONFIG_FILE" | head -n 1 | cut -d\'=\' -f2-)',
        '    EXISTING_HOST=$(grep \'^SKILL_INSIGHT_HOST=\' "$SKILL_INSIGHT_CONFIG_FILE" | head -n 1 | cut -d\'=\' -f2-)',
        '    EXISTING_SHOW_TASK_STATS=$(grep \'^SKILL_INSIGHT_SHOW_TASK_STATS=\' "$SKILL_INSIGHT_CONFIG_FILE" | head -n 1 | cut -d\'=\' -f2-)',
        'fi',
        '',
        '# -- API Key Logic --',
        'FINAL_KEY="$EXISTING_KEY"',
        'if [ -n "$EXISTING_KEY" ]; then',
        '    echo "🔑 Found existing API Key."',
        '    read -p "👉 Use existing key? (y/N, Default: y): " USE_EXISTING < /dev/tty',
        '    if [[ "$USE_EXISTING" =~ ^[Nn]$ ]]; then',
        '        read -p "👉 Please enter your NEW API Key: " FINAL_KEY < /dev/tty',
        '    fi',
        'else',
        '    echo "🔑 SKILL_INSIGHT_API_KEY is not set."',
        '    read -p "👉 Please enter your API Key: " FINAL_KEY < /dev/tty',
        'fi',
        '',
        '# -- Host Logic --',
        'FINAL_HOST="$SKILL_INSIGHT_HOST"',
        'if [ -n "$EXISTING_HOST" ] && [ "$EXISTING_HOST" != "$SKILL_INSIGHT_HOST" ]; then',
        '    echo "🌐 Current Host in config: $EXISTING_HOST"',
        '    echo "🌐 New Host detected: $SKILL_INSIGHT_HOST"',
        '    read -p "👉 Change to new Host? (y/N, Default: y): " CHANGE_HOST < /dev/tty',
        '    if [[ "$CHANGE_HOST" =~ ^[Nn]$ ]]; then',
        '        FINAL_HOST="$EXISTING_HOST"',
        '    fi',
        'elif [ -z "$EXISTING_HOST" ]; then',
        '    FINAL_HOST="$SKILL_INSIGHT_HOST"',
        'fi',
        '',
        'FINAL_SHOW_TASK_STATS="$EXISTING_SHOW_TASK_STATS"',
        'if [ -z "$FINAL_SHOW_TASK_STATS" ]; then',
        '    FINAL_SHOW_TASK_STATS="true"',
        'fi',
        '',
        'if [ -z "$FINAL_KEY" ]; then',
        '    echo "⚠️  Warning: No API Key provided. Telemetry upload will fail until you set it in $SKILL_INSIGHT_CONFIG_FILE"',
        'fi',
        '',
        'echo "⚙️  Updating configuration..."',
        'touch "$SKILL_INSIGHT_CONFIG_FILE"',
        'cp "$SKILL_INSIGHT_CONFIG_FILE" "${SKILL_INSIGHT_CONFIG_FILE}.bak"',
        'grep -v "^SKILL_INSIGHT_HOST=" "${SKILL_INSIGHT_CONFIG_FILE}.bak" | grep -v "^SKILL_INSIGHT_API_KEY=" | grep -v "^SKILL_INSIGHT_SHOW_TASK_STATS=" > "$SKILL_INSIGHT_CONFIG_FILE"',
        'echo "SKILL_INSIGHT_HOST=$FINAL_HOST" >> "$SKILL_INSIGHT_CONFIG_FILE"',
        'echo "SKILL_INSIGHT_API_KEY=$FINAL_KEY" >> "$SKILL_INSIGHT_CONFIG_FILE"',
        'echo "SKILL_INSIGHT_SHOW_TASK_STATS=$FINAL_SHOW_TASK_STATS" >> "$SKILL_INSIGHT_CONFIG_FILE"',
        'rm "${SKILL_INSIGHT_CONFIG_FILE}.bak"',
        'echo "✅ Configuration updated at $SKILL_INSIGHT_CONFIG_FILE"',
        '',
        '# 6. Install Watcher Dependencies',
        'if [ "$INSTALL_CLAUDE" = "true" ] || [ "$INSTALL_OPENCLAW" = "true" ]; then',
        '    echo ""',
        '    echo "📦 Installing watcher dependencies..."',
        '    if command -v npm &> /dev/null; then',
        '      cd "$HOME/.skill-insight"',
        '      if [ ! -f "package.json" ]; then',
        '        echo \'{"name": "skill-insight-watcher", "version": "1.0.0", "type": "module", "dependencies": {}}\' > package.json',
        '      fi',
        '      npm install chokidar --save 2>/dev/null',
        '      echo "✅ Dependencies installed"',
        '    else',
        '      echo "⚠️  npm not found. Skipping dependency installation."',
        '    fi',
        'fi',
        '',
        '# 7. Create Watcher Startup/Stop Scripts',
        'NEEDS_WATCHER_SCRIPTS=false',
        'if [ "$INSTALL_CLAUDE" = "true" ] || [ "$INSTALL_OPENCLAW" = "true" ]; then',
        '    NEEDS_WATCHER_SCRIPTS=true',
        'fi',
        '',
        'if [ "$NEEDS_WATCHER_SCRIPTS" = "true" ]; then',
        '    echo ""',
        '    echo "📝 Creating watcher management scripts..."',
        '',
        '    if [ "$INSTALL_CLAUDE" = "true" ]; then',
        '        cat > "$HOME/.skill-insight/start_claude_watcher.sh" << \'WATCHER_EOF\'',
        '#!/bin/bash',
        'pkill -f "claude_watcher_client.ts" 2>/dev/null',
        'cd "$HOME/.skill-insight" && nohup npx -y tsx "$HOME/.skill-insight/claude_watcher_client.ts" > "$HOME/.skill-insight/logs/claude_watcher.log" 2>&1 &',
        'echo $! > "$HOME/.skill-insight/claude_watcher.pid"',
        'echo "Claude watcher started with PID $(cat $HOME/.skill-insight/claude_watcher.pid)"',
        'WATCHER_EOF',
        '        chmod +x "$HOME/.skill-insight/start_claude_watcher.sh"',
        '',
        '        cat > "$HOME/.skill-insight/stop_claude_watcher.sh" << \'STOP_CLAUDE_EOF\'',
        '#!/bin/bash',
        'pkill -f "claude_watcher_client.ts" 2>/dev/null',
        'rm -f "$HOME/.skill-insight/claude_watcher.pid"',
        'echo "Claude watcher stopped"',
        'STOP_CLAUDE_EOF',
        '        chmod +x "$HOME/.skill-insight/stop_claude_watcher.sh"',
        '    fi',
        '',
        '    if [ "$INSTALL_OPENCLAW" = "true" ]; then',
        '        cat > "$HOME/.skill-insight/start_openclaw_watcher.sh" << \'WATCHER_EOF\'',
        '#!/bin/bash',
        'pkill -f "openclaw_watcher_client.ts" 2>/dev/null',
        'cd "$HOME/.skill-insight" && nohup npx -y tsx "$HOME/.skill-insight/openclaw_watcher_client.ts" > "$HOME/.skill-insight/logs/openclaw_watcher.log" 2>&1 &',
        'echo $! > "$HOME/.skill-insight/openclaw_watcher.pid"',
        'echo "OpenClaw watcher started with PID $(cat $HOME/.skill-insight/openclaw_watcher.pid)"',
        'WATCHER_EOF',
        '        chmod +x "$HOME/.skill-insight/start_openclaw_watcher.sh"',
        '',
        '        cat > "$HOME/.skill-insight/stop_openclaw_watcher.sh" << \'STOP_OPENCLAW_EOF\'',
        '#!/bin/bash',
        'pkill -f "openclaw_watcher_client.ts" 2>/dev/null',
        'rm -f "$HOME/.skill-insight/openclaw_watcher.pid"',
        'echo "OpenClaw watcher stopped"',
        'STOP_OPENCLAW_EOF',
        '        chmod +x "$HOME/.skill-insight/stop_openclaw_watcher.sh"',
        '    fi',
        '',
        '    cat > "$HOME/.skill-insight/start_watchers.sh" << \'WATCHER_HEADER\'',
        '#!/bin/bash',
        'echo "Starting Skill-Insight watchers..."',
        'WATCHER_HEADER',
        '    if [ "$INSTALL_CLAUDE" = "true" ]; then echo \'"$HOME/.skill-insight/start_claude_watcher.sh"\' >> "$HOME/.skill-insight/start_watchers.sh"; fi',
        '    if [ "$INSTALL_OPENCLAW" = "true" ]; then echo \'"$HOME/.skill-insight/start_openclaw_watcher.sh"\' >> "$HOME/.skill-insight/start_watchers.sh"; fi',
        '    echo \'echo "All watchers started!"\' >> "$HOME/.skill-insight/start_watchers.sh"',
        '    chmod +x "$HOME/.skill-insight/start_watchers.sh"',
        '',
        '    cat > "$HOME/.skill-insight/stop_watchers.sh" << \'STOP_HEADER\'',
        '#!/bin/bash',
        'echo "Stopping Skill-Insight watchers..."',
        'STOP_HEADER',
        '    if [ "$INSTALL_CLAUDE" = "true" ]; then echo \'"$HOME/.skill-insight/stop_claude_watcher.sh"\' >> "$HOME/.skill-insight/stop_watchers.sh"; fi',
        '    if [ "$INSTALL_OPENCLAW" = "true" ]; then echo \'"$HOME/.skill-insight/stop_openclaw_watcher.sh"\' >> "$HOME/.skill-insight/stop_watchers.sh"; fi',
        '    echo \'echo "All watchers stopped!"\' >> "$HOME/.skill-insight/stop_watchers.sh"',
        '    chmod +x "$HOME/.skill-insight/stop_watchers.sh"',
        'fi',
        '',
        '# 8. Start Watchers Now',
        'if [ "$NEEDS_WATCHER_SCRIPTS" = "true" ]; then',
        '    echo ""',
        '    echo "🚀 Starting telemetry watchers..."',
        '    if command -v npx &> /dev/null; then',
        '        "$HOME/.skill-insight/start_watchers.sh"',
        '    else',
        '        echo "⚠️  Node.js (npx) not found. Skipping watcher startup."',
        '    fi',
        'fi',
        '',
        '# 10. Final Summary',
        'echo ""',
        'echo "🌟 Skill-Insight Telemetry: READY"',
        'echo "------------------------------------------------"',
        'echo "Installed Components:"',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  ✅ OpenCode Plugin: ~/.opencode/plugins/Witty-Skill-Insight.ts"; fi',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  ✅ OpenCode Command: ~/.config/opencode/commands/si-optimizer.md"; fi',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then echo "  ✅ Claude Watcher: ~/.skill-insight/claude_watcher_client.ts"; fi',
        'if [ "$INSTALL_OPENCLAW" = "true" ]; then echo "  ✅ OpenClaw Watcher: ~/.skill-insight/openclaw_watcher_client.ts"; fi',
        '',
        'if [ "$NEEDS_WATCHER_SCRIPTS" = "true" ]; then',
        '    echo ""',
        '    echo "Watcher Management:"',
        '    echo "  Start all:    ~/.skill-insight/start_watchers.sh"',
        '    echo "  Stop all:     ~/.skill-insight/stop_watchers.sh"',
        '    echo "  Logs:         ~/.skill-insight/logs/"',
        'fi',
        '',
        'echo ""',
        'echo "Usage:"',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  1. Run: opencode run \'hello\'"; fi',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then echo "  2. Run: claude (restart terminal first)"; fi',
        'if [ "$INSTALL_OPENCLAW" = "true" ]; then echo "  3. OpenClaw will automatically monitor and upload telemetry"; fi',
        'echo "------------------------------------------------"',
    ];
    return lines.join('\n');
}

function generatePowerShellScript(host: string, baseUrl: string): string {
    const lines = [
        '# =============================================================================',
        '# Skill-insight One-Click Setup (PowerShell)',
        '# =============================================================================',
        '',
        '$SKILL_INSIGHT_HOST = "' + host + '"',
        '$SKILL_INSIGHT_BASE_URL = "' + baseUrl + '"',
        '',
        'Write-Host "🚀 Fetching Skill-insight telemetry components from $SKILL_INSIGHT_BASE_URL..."',
        '',
        '# 1. Setup Directories',
        '$homeDir = $env:USERPROFILE',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.skill-insight" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.skill-insight\\logs" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.opencode\\plugins" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.opencode\\skills" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.claude\\projects" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.openclaw\\agents" | Out-Null',
        'New-Item -ItemType Directory -Force -Path ".opencode\\skills" | Out-Null',
        'Write-Host "📂 Created necessary directories"',
        '',
        '# 2. Interactive Framework Selection with inquirer',
        'Write-Host ""',
        '',
        '$SELECTOR_SCRIPT = "$homeDir\\.skill-insight\\framework_selector.mjs"',
        '$SELECTOR_RESULT = "$homeDir\\.skill-insight\\.selector_result"',
        '',
        '# Install inquirer if not already installed',
        'Set-Location "$homeDir\\.skill-insight"',
        'if (-not (Test-Path "node_modules\\inquirer")) {',
        '    Write-Host "📦 Installing inquirer for interactive selection..."',
        '    npm install inquirer --save 2>$null',
        '}',
        '',
        '$selectorContent = @\'',
        'import inquirer from \'inquirer\';',
        'import fs from \'fs\';',
        '',
        'const frameworks = [',
        '    { name: \'OpenCode\', value: \'opencode\' },',
        '    { name: \'Claude Code\', value: \'claude\' },',
        '    { name: \'OpenClaw\', value: \'openclaw\' }',
        '];',
        '',
        'async function select() {',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╔══════════════════════════════════════════════════════════╗\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[1m\\x1b[36m%s\\x1b[0m\', \'║                 ✨ Skill-insight ✨                      ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╚══════════════════════════════════════════════════════════╝\');',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[90m%s\\x1b[0m\', \'  提示: ↑↓ 移动  |  空格 选择  |  a 全选  |  i 反选  |  Enter 确认\');',
        '    console.log(\'\');',
        '',
        '    const answers = await inquirer.prompt([',
        '        {',
        '            type: \'checkbox\',',
        '            name: \'frameworks\',',
        '            message: \'集成到：\',',
        '            choices: frameworks,',
        '            pageSize: 10,',
        '            loop: false',
        '        }',
        '    ]);',
        '',
        '    const selected = answers.frameworks;',
        '    ',
        '    if (selected.length > 0) {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[32m%s\\x1b[0m\', \'✅ 将安装以下组件:\');',
        '        selected.forEach(fw => {',
        '            const name = frameworks.find(f => f.value === fw)?.name || fw;',
        '            console.log(\'\\x1b[32m%s\\x1b[0m\', \'   • \' + name);',
        '        });',
        '        console.log(\'\');',
        '    } else {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[33m%s\\x1b[0m\', \'⚠️  未选择任何组件，将不进行安装。\');',
        '        console.log(\'\');',
        '    }',
        '',
        '    const resultFile = process.env.SELECTOR_RESULT_FILE || process.env.USERPROFILE + \'\\\\.skill-insight\\\\.selector_result\';',
        '    fs.writeFileSync(resultFile, selected.join(\',\'));',
        '}',
        '',
        'select().catch(err => {',
        '    console.error(\'Error:\', err);',
        '    process.exit(1);',
        '});',
        '\'@',
        '',
        'Set-Content -Path $SELECTOR_SCRIPT -Value $selectorContent -Encoding UTF8',
        '',
        '# Run the selector interactively',
        '$env:SELECTOR_RESULT_FILE = $SELECTOR_RESULT',
        'Set-Location "$homeDir\\.skill-insight"',
        'npx -y tsx $SELECTOR_SCRIPT',
        '',
        '# Read the selection result from file',
        'if (Test-Path $SELECTOR_RESULT) {',
        '    $SELECTED_FRAMEWORKS = Get-Content $SELECTOR_RESULT',
        '    Remove-Item $SELECTOR_RESULT -Force',
        '} else {',
        '    $SELECTED_FRAMEWORKS = ""',
        '}',
        '',
        '# Set installation flags based on selection',
        '$INSTALL_OPENCODE = $false',
        '$INSTALL_CLAUDE = $false',
        '$INSTALL_OPENCLAW = $false',
        '',
        'if ($SELECTED_FRAMEWORKS -match "opencode") {',
        '    $INSTALL_OPENCODE = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "claude") {',
        '    $INSTALL_CLAUDE = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "openclaw") {',
        '    $INSTALL_OPENCLAW = $true',
        '}',
        '',
        '# Exit if nothing selected',
        'if (-not $INSTALL_OPENCODE -and -not $INSTALL_CLAUDE -and -not $INSTALL_OPENCLAW) {',
        '    Write-Host "⚠️  未选择任何框架组件，将跳过插件安装。"',
        '    Write-Host "   继续执行配置步骤..."',
        '    Write-Host ""',
        '}',
        '',
        '# 3. Download Components',
        'if ($INSTALL_OPENCODE) {',
        '    Write-Host "⏬ Downloading OpenCode Plugin..."',
        '    $opencodeConfigDir = if ($env:XDG_CONFIG_HOME) { Join-Path $env:XDG_CONFIG_HOME "opencode" } elseif ($env:APPDATA) { Join-Path $env:APPDATA "opencode" } else { Join-Path $homeDir ".config\\opencode" }',
        '    New-Item -ItemType Directory -Path (Join-Path $opencodeConfigDir "plugins") -Force | Out-Null',
        '    Invoke-WebRequest -Uri "$SKILL_INSIGHT_BASE_URL/api/setup/opencode" -OutFile (Join-Path $opencodeConfigDir "plugins\\Witty-Skill-Insight.ts")',
        '    Copy-Item (Join-Path $opencodeConfigDir "plugins\\Witty-Skill-Insight.ts") "$homeDir\\.opencode\\plugins\\Witty-Skill-Insight.ts" -Force -ErrorAction SilentlyContinue',
        '    Write-Host "⏬ Downloading OpenCode TUI Plugin..."',
        '    $tuiPluginPath = (Join-Path $opencodeConfigDir "plugins\\Witty-Skill-Insight.tui.tsx")',
        '    Invoke-WebRequest -Uri "$SKILL_INSIGHT_BASE_URL/api/setup/opencode-tui" -OutFile $tuiPluginPath',
        '    Copy-Item $tuiPluginPath "$homeDir\\.opencode\\plugins\\Witty-Skill-Insight.tui.tsx" -Force -ErrorAction SilentlyContinue',
        '    $tuiConfigFile = (Join-Path $opencodeConfigDir "tui.json")',
        '    try {',
        '        $data = @{}',
        '        if (Test-Path $tuiConfigFile) {',
        '            $raw = Get-Content $tuiConfigFile -Raw',
        '            if ($raw -and $raw.Trim()) { $data = $raw | ConvertFrom-Json }',
        '        }',
        '        if (-not $data.plugin) { $data | Add-Member -MemberType NoteProperty -Name plugin -Value @() -Force }',
        '        if ($data.plugin -notcontains $tuiPluginPath) { $data.plugin += $tuiPluginPath }',
        '        $data | ConvertTo-Json -Depth 10 | Set-Content -Path $tuiConfigFile -Encoding UTF8',
        '    } catch {',
        '        Write-Host "⚠️  Failed to patch tui.json for TUI plugin."',
        '    }',
        '}',
        '',
        'if ($INSTALL_CLAUDE) {',
        '    Write-Host "⏬ Downloading Claude Code Watcher..."',
        '    Invoke-WebRequest -Uri "$SKILL_INSIGHT_BASE_URL/api/setup/claude-watcher" -OutFile "$homeDir\\.skill-insight\\claude_watcher_client.ts"',
        '}',
        '',
        'if ($INSTALL_OPENCLAW) {',
        '    Write-Host "⏬ Downloading OpenClaw Watcher..."',
        '    Invoke-WebRequest -Uri "$SKILL_INSIGHT_BASE_URL/api/setup/openclaw-watcher" -OutFile "$homeDir\\.skill-insight\\openclaw_watcher_client.ts"',
        '}',
        '',
        '# 4. Configure ~/.skill-insight/.env',
        '$SKILL_INSIGHT_CONFIG_FILE = "$homeDir\\.skill-insight\\.env"',
        '$EXISTING_KEY = ""',
        '$EXISTING_HOST = ""',
        '$EXISTING_SHOW_TASK_STATS = ""',
        'if (Test-Path $SKILL_INSIGHT_CONFIG_FILE) {',
        '    $content = Get-Content $SKILL_INSIGHT_CONFIG_FILE',
        '    $keyLine = $content | Select-String \'^SKILL_INSIGHT_API_KEY=\' | Select-Object -First 1',
        '    $hostLine = $content | Select-String \'^SKILL_INSIGHT_HOST=\' | Select-Object -First 1',
        '    $showLine = $content | Select-String \'^SKILL_INSIGHT_SHOW_TASK_STATS=\' | Select-Object -First 1',
        '    if ($keyLine) {',
        '        $EXISTING_KEY = $keyLine.Line.Substring(\'SKILL_INSIGHT_API_KEY=\'.Length)',
        '    }',
        '    if ($hostLine) {',
        '        $EXISTING_HOST = $hostLine.Line.Substring(\'SKILL_INSIGHT_HOST=\'.Length)',
        '    }',
        '    if ($showLine) {',
        '        $EXISTING_SHOW_TASK_STATS = $showLine.Line.Substring(\'SKILL_INSIGHT_SHOW_TASK_STATS=\'.Length)',
        '    }',
        '}',
        '',
        '# -- API Key Logic --',
        '$FINAL_KEY = $EXISTING_KEY',
        'if ($EXISTING_KEY) {',
        '    Write-Host "🔑 Found existing API Key."',
        '    $USE_EXISTING = Read-Host "👉 Use existing key? (y/N, Default: y)"',
        '    if ($USE_EXISTING -match \'^[Nn]$\') {',
        '        $FINAL_KEY = Read-Host "👉 Please enter your NEW API Key"',
        '    }',
        '} else {',
        '    Write-Host "🔑 SKILL_INSIGHT_API_KEY is not set."',
        '    $FINAL_KEY = Read-Host "👉 Please enter your API Key"',
        '}',
        '',
        '# -- Host Logic --',
        '$FINAL_HOST = $SKILL_INSIGHT_HOST',
        'if ($EXISTING_HOST -and ($EXISTING_HOST -ne $SKILL_INSIGHT_HOST)) {',
        '    Write-Host "🌐 Current Host in config: $EXISTING_HOST"',
        '    Write-Host "🌐 New Host detected: $SKILL_INSIGHT_HOST"',
        '    $CHANGE_HOST = Read-Host "👉 Change to new Host? (y/N, Default: y)"',
        '    if ($CHANGE_HOST -match \'^[Nn]$\') {',
        '        $FINAL_HOST = $EXISTING_HOST',
        '    }',
        '} elseif (-not $EXISTING_HOST) {',
        '    $FINAL_HOST = $SKILL_INSIGHT_HOST',
        '}',
        '',
        '$FINAL_SHOW_TASK_STATS = $EXISTING_SHOW_TASK_STATS',
        'if (-not $FINAL_SHOW_TASK_STATS) {',
        '    $FINAL_SHOW_TASK_STATS = "true"',
        '}',
        '',
        'if (-not $FINAL_KEY) {',
        '    Write-Host "⚠️  Warning: No API Key provided. Telemetry upload will fail until you set it in $SKILL_INSIGHT_CONFIG_FILE"',
        '}',
        '',
        'Write-Host "⚙️  Updating configuration..."',
        'New-Item -ItemType File -Path $SKILL_INSIGHT_CONFIG_FILE -Force | Out-Null',
        'Copy-Item $SKILL_INSIGHT_CONFIG_FILE "$SKILL_INSIGHT_CONFIG_FILE.bak"',
        '$content = Get-Content "$SKILL_INSIGHT_CONFIG_FILE.bak"',
        '$content | Where-Object { $_ -notmatch \'^SKILL_INSIGHT_HOST=\' -and $_ -notmatch \'^SKILL_INSIGHT_API_KEY=\' -and $_ -notmatch \'^SKILL_INSIGHT_SHOW_TASK_STATS=\' } | Set-Content $SKILL_INSIGHT_CONFIG_FILE',
        'Add-Content $SKILL_INSIGHT_CONFIG_FILE "SKILL_INSIGHT_HOST=$FINAL_HOST"',
        'Add-Content $SKILL_INSIGHT_CONFIG_FILE "SKILL_INSIGHT_API_KEY=$FINAL_KEY"',
        'Add-Content $SKILL_INSIGHT_CONFIG_FILE "SKILL_INSIGHT_SHOW_TASK_STATS=$FINAL_SHOW_TASK_STATS"',
        'Remove-Item "$SKILL_INSIGHT_CONFIG_FILE.bak" -Force',
        'Write-Host "✅ Configuration updated at $SKILL_INSIGHT_CONFIG_FILE"',
        '',
        '# 6. Install Watcher Dependencies',
        'if ($INSTALL_CLAUDE -or $INSTALL_OPENCLAW) {',
        '    Write-Host ""',
        '    Write-Host "📦 Installing watcher dependencies..."',
        '    if (Get-Command npm -ErrorAction SilentlyContinue) {',
        '        Set-Location "$homeDir\\.skill-insight"',
        '        if (-not (Test-Path "package.json")) {',
        '            \'{"name": "skill-insight-watcher", "version": "1.0.0", "type": "module", "dependencies": {}}\' | Out-File -FilePath "package.json" -Encoding utf8',
        '        }',
        '        npm install chokidar --save 2>$null',
        '        Write-Host "✅ Dependencies installed"',
        '    } else {',
        '        Write-Host "⚠️  npm not found. Skipping dependency installation."',
        '    }',
        '}',
        '',
        '# 7. Create Watcher Startup/Stop Scripts',
        '$NEEDS_WATCHER_SCRIPTS = $false',
        'if ($INSTALL_CLAUDE -or $INSTALL_OPENCLAW) {',
        '    $NEEDS_WATCHER_SCRIPTS = $true',
        '}',
        '',
        'if ($NEEDS_WATCHER_SCRIPTS) {',
        '    Write-Host ""',
        '    Write-Host "📝 Creating watcher management scripts..."',
        '',
        '    if ($INSTALL_CLAUDE) {',
        '        $startScript = @\'',
        'pkill -f "claude_watcher_client.ts" 2>/dev/null',
        'Set-Location "$env:USERPROFILE\\.skill-insight"',
        'Start-Process -FilePath "npx" -ArgumentList "-y", "tsx", "$env:USERPROFILE\\.skill-insight\\claude_watcher_client.ts" -RedirectStandardOutput "$env:USERPROFILE\\.skill-insight\\logs\\claude_watcher.log" -RedirectStandardError "$env:USERPROFILE\\.skill-insight\\logs\\claude_watcher_error.log" -NoNewWindow',
        'Write-Host "Claude watcher started"',
        '\'@',
        '        Set-Content -Path "$homeDir\\.skill-insight\\start_claude_watcher.ps1" -Value $startScript -Encoding UTF8',
        '',
        '        $stopScript = @\'',
        'Get-Process | Where-Object { $_.CommandLine -like "*claude_watcher_client.ts*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        'Remove-Item "$env:USERPROFILE\\.skill-insight\\claude_watcher.pid" -Force -ErrorAction SilentlyContinue',
        'Write-Host "Claude watcher stopped"',
        '\'@',
        '        Set-Content -Path "$homeDir\\.skill-insight\\stop_claude_watcher.ps1" -Value $stopScript -Encoding UTF8',
        '    }',
        '',
        '    if ($INSTALL_OPENCLAW) {',
        '        $startScript = @\'',
        'pkill -f "openclaw_watcher_client.ts" 2>/dev/null',
        'Set-Location "$env:USERPROFILE\\.skill-insight"',
        'Start-Process -FilePath "npx" -ArgumentList "-y", "tsx", "$env:USERPROFILE\\.skill-insight\\openclaw_watcher_client.ts" -RedirectStandardOutput "$env:USERPROFILE\\.skill-insight\\logs\\openclaw_watcher.log" -RedirectStandardError "$env:USERPROFILE\\.skill-insight\\logs\\openclaw_watcher_error.log" -NoNewWindow',
        'Write-Host "OpenClaw watcher started"',
        '\'@',
        '        Set-Content -Path "$homeDir\\.skill-insight\\start_openclaw_watcher.ps1" -Value $startScript -Encoding UTF8',
        '',
        '        $stopScript = @\'',
        'Get-Process | Where-Object { $_.CommandLine -like "*openclaw_watcher_client.ts*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        'Remove-Item "$env:USERPROFILE\\.skill-insight\\openclaw_watcher.pid" -Force -ErrorAction SilentlyContinue',
        'Write-Host "OpenClaw watcher stopped"',
        '\'@',
        '        Set-Content -Path "$homeDir\\.skill-insight\\stop_openclaw_watcher.ps1" -Value $stopScript -Encoding UTF8',
        '    }',
        '',
        '    $combinedStart = \'Write-Host "Starting Skill-Insight watchers..."\'',
        '    if ($INSTALL_CLAUDE) { $combinedStart += [char]10 + "& `"$homeDir\\.skill-insight\\start_claude_watcher.ps1`"" }',
        '    if ($INSTALL_OPENCLAW) { $combinedStart += [char]10 + "& `"$homeDir\\.skill-insight\\start_openclaw_watcher.ps1`"" }',
        '    $combinedStart += [char]10 + \'Write-Host "All watchers started!"\'',
        '    Set-Content -Path "$homeDir\\.skill-insight\\start_watchers.ps1" -Value $combinedStart -Encoding UTF8',
        '',
        '    $combinedStop = \'Write-Host "Stopping Skill-Insight watchers..."\'',
        '    if ($INSTALL_CLAUDE) { $combinedStop += [char]10 + "& `"$homeDir\\.skill-insight\\stop_claude_watcher.ps1`"" }',
        '    if ($INSTALL_OPENCLAW) { $combinedStop += [char]10 + "& `"$homeDir\\.skill-insight\\stop_openclaw_watcher.ps1`"" }',
        '    $combinedStop += [char]10 + \'Write-Host "All watchers stopped!"\'',
        '    Set-Content -Path "$homeDir\\.skill-insight\\stop_watchers.ps1" -Value $combinedStop -Encoding UTF8',
        '}',
        '',
        '# 8. Start Watchers Now',
        'if ($NEEDS_WATCHER_SCRIPTS) {',
        '    Write-Host ""',
        '    Write-Host "🚀 Starting telemetry watchers..."',
        '    if (Get-Command npx -ErrorAction SilentlyContinue) {',
        '        & "$homeDir\\.skill-insight\\start_watchers.ps1"',
        '    } else {',
        '        Write-Host "⚠️  Node.js (npx) not found. Skipping watcher startup."',
        '    }',
        '}',
        '',
        '# 10. Final Summary',
        'Write-Host ""',
        'Write-Host "🌟 Skill-Insight Telemetry: READY"',
        'Write-Host "------------------------------------------------"',
        'Write-Host "Installed Components:"',
        'if ($INSTALL_OPENCODE) { Write-Host "  ✅ OpenCode Plugin: ~/.opencode/plugins/Witty-Skill-Insight.ts" }',
        'if ($INSTALL_CLAUDE) { Write-Host "  ✅ Claude Watcher: ~/.skill-insight/claude_watcher_client.ts" }',
        'if ($INSTALL_OPENCLAW) { Write-Host "  ✅ OpenClaw Watcher: ~/.skill-insight/openclaw_watcher_client.ts" }',
        '',
        'if ($NEEDS_WATCHER_SCRIPTS) {',
        '    Write-Host ""',
        '    Write-Host "Watcher Management:"',
        '    Write-Host "  Start all:    ~/.skill-insight/start_watchers.ps1"',
        '    Write-Host "  Stop all:     ~/.skill-insight/stop_watchers.ps1"',
        '    Write-Host "  Logs:         ~/.skill-insight/logs/"',
        '}',
        '',
        'Write-Host ""',
        'Write-Host "Usage:"',
        'if ($INSTALL_OPENCODE) { Write-Host "  1. Run: opencode run \'hello\'" }',
        'if ($INSTALL_CLAUDE) { Write-Host "  2. Run: claude (restart terminal first)" }',
        'if ($INSTALL_OPENCLAW) { Write-Host "  3. OpenClaw will automatically monitor and upload telemetry" }',
        'Write-Host "------------------------------------------------"',
    ];
    return lines.join('\n');
}

export async function GET(request: Request) {
    const host = request.headers.get('x-forwarded-host') || request.headers.get('host') || '127.0.0.1:3000';
    const protocol = request.headers.get('x-forwarded-proto') || 'https';

    // Detect base path from request URL (e.g., /skill-insight/api/setup -> /skill-insight)
    const requestUrl = new URL(request.url);
    const basePath = requestUrl.pathname.replace(/\/api\/setup\/?$/, '');
    // --- 直接读取环境变量，不再通过 pathname 截取 ---
    const urlPrefix = process.env.NEXT_PUBLIC_URL_PREFIX || '';
    const baseUrl = `${protocol}://${host}${urlPrefix}`;
    const skillInsightHost = baseUrl;

    const platform = detectPlatform(request);

    if (platform === 'windows') {
        const script = generatePowerShellScript(skillInsightHost, baseUrl);
        return new NextResponse(script, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
            },
        });
    } else {
        const script = generateBashScript(skillInsightHost, baseUrl);
        return new NextResponse(script, {
            headers: {
                'Content-Type': 'text/x-shellscript',
            },
        });
    }
}
